# Generated by Django 2.2.7 on 2020-08-02 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('comment_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='Books_post_book_id_4dd719_idx',
        ),
        migrations.RemoveIndex(
            model_name='thread',
            name='Books_threa_book_id_a87f20_idx',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='thread_visits',
            new_name='thread_views',
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['book_id', 'thread_id', 'id'], name='Books_post_book_id_554d62_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['book_id', 'chapter_id', 'id'], name='Books_threa_book_id_c1b06b_idx'),
        ),
        migrations.AddField(
            model_name='comment',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.Book'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='thread_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.Thread'),
        ),
    ]
