# Generated by Django 2.2.7 on 2020-08-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
