# Generated by Django 2.2.7 on 2020-08-03 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_auto_20200802_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_name',
            new_name='book_title',
        ),
    ]
