# Generated by Django 2.2.7 on 2020-08-03 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_auto_20200803_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='chapter_threads_count',
        ),
    ]
