# Generated by Django 2.2.7 on 2020-08-03 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_auto_20200803_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='chapter_name',
            new_name='chapter_title',
        ),
    ]
